swagger: '2.0'
info:
  version: 1.0.0
  title: The MedicSoft MongoDB REST API(s)
host: localhost:4000
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  "/v1/clients":
    get:
      summary: Get all clients
      produces:
      - application/json
      responses:
        '200':
          description: success
    post:
      summary: Create a client
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: body
        name: client
        required: true
        schema:
          $ref: "#/definitions/Client"
      responses:
        '200':
          description: Created
  /v1/clients/{email}:
    get:
      summary: Get client by email address
      produces:
      - application/json
      parameters:
      - in: path
        name: email
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success

definitions:
  Client:
    type: object
    properties:
      firstName:
        type: String
      lastName:
        type: String
      address:
        type: object
        properties:
          line1:
            type: String
            required: true
          line2:
            type: String
          zipCode: 
            type: Number
          state:
            type: String
          country:
            type: String
      contacts:
        type: object
        properties:
          phones:
            type: array
            style: simple
            items:
              type: string
          email:
            type: String
            required: true
